name: should
description: A simple, extensible, readable BDD assertion library. Supports introspective terminal output.
version: 0.1.1+1
homepage: https://github.com/AKushWarrior/should

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
  dartx: ^0.5.0
  logger: ^0.9.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
